# Generated by Django 3.2.7 on 2021-10-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formularioPQRS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('0', 'Cédula de ciudadanía'), ('1', 'Cédula de extranjería'), ('2', 'NIT')], max_length=12, verbose_name='Típo de documento')),
                ('identificacion', models.CharField(max_length=12, verbose_name='Número documento')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('locate_hppnd', models.CharField(choices=[('0', 'Oficinas'), ('1', 'Centros de atención'), ('2', 'Telefónico')], max_length=50, verbose_name='ubicación del hecho')),
                ('city_name', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('dscrp_happ', models.CharField(max_length=250, verbose_name='Descripción de hechos')),
            ],
        ),
    ]
