# Generated by Django 3.2.7 on 2021-10-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sede', models.CharField(help_text='nombre sede', max_length=20)),
                ('direccion_sede', models.CharField(max_length=50)),
                ('telefono_sede', models.CharField(max_length=50)),
                ('correo_sede', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
                'ordering': ['nombre_sede'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=40)),
                ('edad', models.PositiveIntegerField(default=0)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('especialidad', models.CharField(max_length=30)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.sede')),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_consultorio', models.CharField(max_length=3)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.sede')),
            ],
            options={
                'ordering': ['sede'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('Historia', models.ImageField(blank=True, null=True, upload_to='history')),
                ('consultorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.consultorio')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.sede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendar.usuario')),
            ],
            options={
                'verbose_name': 'consulta',
                'verbose_name_plural': 'consultas',
            },
        ),
    ]
